### ISSUE TITLE
App crash due to SigninView 

### ISSUE THREAD

**Issue by rokon-mlbd** [CiscoDevNet/DNASpacesSDKSampleApp-IOS#4]
Xcode is not able to identify SigninView. So it is not possible to subclass from `SigninView` (select SigninView class from Xcode identity inspector). As a result app crashes when outlet is drown from a subView of ` SigninView`
<img width="830" alt="Screen Shot 2022-08-25 at 6 10 58 PM" src="https://user-images.githubusercontent.com/29856113/186662726-79879221-6ef9-46db-9318-df3c256dce45.png">

**Comment by rajeshkr36** [comment]
There was issue with the mismatch of the identifier used to load the SigningView nib file. This issue is resolve
